import { Router } from 'express';
import { checkEmail, deleteAccount, disableTwoFactor, enableTwoFactor, forgotPassword, getMe, login, logout, refresh, register, requestEmailChange, requestPasswordChange, resendTwoFactorLoginCode, resetPassword, updateProfile, verifyEmail, verifyEmailChange, verifyPasswordChange, verifyResetCode, verifyTwoFactorLogin, verifyTwoFactorSetup } from '../controllers/authController.js';
import { allowRoles, protect } from '../middleware/auth.js';
import { validateChangeCode, validateEmail, validateEmailChangeRequest, validateEmailVerification, validateLogin, validatePasswordChangeRequest, validateProfile, validateRegister, validateResetCode, validateResetPassword } from '../middleware/validate.js';
import { logActivity } from '../utils/logActivity.js';
import { authLimiter, emailChangeRequestLimiter, emailChangeVerifyLimiter, forgotPasswordLimiter, passwordChangeRequestLimiter, passwordChangeVerifyLimiter, resetPasswordLimiter } from '../middleware/rateLimit.js';

const router = Router();
router.use(authLimiter);
router.get('/check-email', checkEmail);
router.post('/verify-email', validateEmailVerification, verifyEmail);
router.post('/register', validateRegister, register);
router.post('/login', validateLogin, login);
router.post('/2fa/verify', verifyTwoFactorLogin);
router.post('/2fa/resend', resendTwoFactorLoginCode);
router.post('/2fa/enable', protect, allowRoles('superadmin', 'admin', 'barangay'), enableTwoFactor);
router.post('/2fa/enable/verify', protect, allowRoles('superadmin', 'admin', 'barangay'), verifyTwoFactorSetup);
router.post('/2fa/disable', protect, allowRoles('superadmin', 'admin', 'barangay'), disableTwoFactor);
router.post('/refresh', protect, refresh);
router.post('/logout', protect, logout);
router.get('/me', protect, getMe);
router.post('/request-email-change', protect, emailChangeRequestLimiter, validateEmailChangeRequest, requestEmailChange);
router.post('/verify-email-change', protect, emailChangeVerifyLimiter, validateChangeCode, verifyEmailChange);
router.post('/request-password-change', protect, passwordChangeRequestLimiter, validatePasswordChangeRequest, requestPasswordChange);
router.post('/verify-password-change', protect, passwordChangeVerifyLimiter, validateChangeCode, verifyPasswordChange);
router.put('/profile', protect, validateProfile, updateProfile);
router.delete('/account', protect, deleteAccount);
router.post('/forgot-password', forgotPasswordLimiter, validateEmail, forgotPassword);
router.post('/verify-reset-code', validateResetCode, verifyResetCode);
router.post('/reset-password', resetPasswordLimiter, validateResetPassword, resetPassword);
export default router;
