import { Router } from 'express';
import { changePassword, checkEmail, deleteAccount, disableTwoFactor, enableTwoFactor, forgotPassword, getMe, login, logout, refresh, register, resendTwoFactorLoginCode, resetPassword, updateProfile, verifyEmail, verifyResetCode, verifyTwoFactorLogin, verifyTwoFactorSetup } from '../controllers/authController.js';
import { allowRoles, protect } from '../middleware/auth.js';
import { passwordPolicy, validateBadRequest, validateEmail, validateEmailVerification, validateLogin, validateProfile, validateRegister, validateResetCode, validateResetPassword } from '../middleware/validate.js';
import { logActivity } from '../utils/logActivity.js';
import { authLimiter, forgotPasswordLimiter, resetPasswordLimiter } from '../middleware/rateLimit.js';

const router = Router();
router.use(authLimiter);
router.get('/check-email', checkEmail);
router.post('/verify-email', validateEmailVerification, verifyEmail);
router.post('/register', validateRegister, register);
router.post('/login', validateLogin, login);
router.post('/2fa/verify', verifyTwoFactorLogin);
router.post('/2fa/resend', resendTwoFactorLoginCode);
router.post('/2fa/enable', protect, allowRoles('superadmin', 'admin', 'barangay'), enableTwoFactor);
router.post('/2fa/enable/verify', protect, allowRoles('superadmin', 'admin', 'barangay'), verifyTwoFactorSetup);
router.post('/2fa/disable', protect, allowRoles('superadmin', 'admin', 'barangay'), disableTwoFactor);
router.post('/refresh', protect, refresh);
router.post('/logout', protect, logout);
router.get('/me', protect, getMe);
router.post('/change-password', protect, passwordPolicy('newPassword'), validateBadRequest, changePassword);
router.put('/profile', protect, validateProfile, updateProfile);
router.delete('/account', protect, deleteAccount);
router.post('/forgot-password', forgotPasswordLimiter, validateEmail, forgotPassword);
router.post('/verify-reset-code', validateResetCode, verifyResetCode);
router.post('/reset-password', resetPasswordLimiter, validateResetPassword, resetPassword);
export default router;
