import React from 'react';

const UserFormModal = ({ isOpen, isDark, form, roleOptions, isCreating = true, onChange, onClose, onSubmit, saving = false }) => {
  if (!isOpen) return null;
  const inputClass = `mt-1 w-full rounded-lg border px-3 py-2 ${isDark ? 'border-[#2e303a] bg-[#0a0b0f] text-white' : 'border-slate-200 bg-white text-slate-900'}`;
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4"><form onSubmit={onSubmit} className={`w-full max-w-lg rounded-2xl border p-6 ${isDark ? 'border-[#2e303a] bg-[#14151d]' : 'border-slate-200 bg-white'}`}><div className="mb-4 flex items-center justify-between"><h3 className={`text-xl font-bold ${isDark ? 'text-white' : 'text-slate-900'}`}>{isCreating ? 'Add user' : 'Edit user'}</h3><button type="button" onClick={onClose} className="text-sm text-gray-400 hover:text-white">Close</button></div><div className="space-y-4"><label className="block text-sm"><span>Full name</span><input required value={form.name} onChange={(event) => onChange('name', event.target.value)} className={inputClass} /></label><label className="block text-sm"><span>Email</span><input required type="email" value={form.email} onChange={(event) => onChange('email', event.target.value)} className={inputClass} /></label>{isCreating && <label className="block text-sm"><span>Password</span><input required type="password" minLength="8" value={form.password} onChange={(event) => onChange('password', event.target.value)} className={inputClass} /></label>}<label className="block text-sm"><span>Role</span><select required value={form.role} onChange={(event) => onChange('role', event.target.value)} className={inputClass}>{roleOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>{form.role === 'barangay' && <label className="block text-sm"><span>Barangay</span><select required value={form.barangay} onChange={(event) => onChange('barangay', event.target.value)} className={inputClass}><option value="">Select barangay</option><option value="Bonuan">Bonuan</option><option value="Lucao">Lucao</option><option value="Tapuac">Tapuac</option></select></label>}</div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-lg border border-[#2e303a] px-4 py-2 text-sm text-gray-300">Cancel</button><button type="submit" disabled={saving} className="rounded-lg bg-[#3b82f6] px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{isCreating ? 'Create user' : 'Save changes'}</button></div></form></div>;
};

export default UserFormModal;
